version: '3'

services:
  app:
    image: 'php:8.2-cli'
    volumes:
      - '.:/app'
    working_dir: /app
    environment:
      - OGINI_BASE_URL=http://ogini:3000
      - OGINI_API_KEY=development-key

  ogini:
    image: 'local/ogini:latest'  # Replace with actual OginiSearch image
    ports:
      - '3000:3000'
    volumes:
      - 'ogini-data:/data'
    environment:
      - NODE_ENV=development

volumes:
  ogini-data: 