name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! This helps us improve the OginiSearch Laravel Scout Driver.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Before reporting a bug, please check the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using a supported version of Laravel and PHP
          required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: Which version of ogini/oginisearch-laravel-scout are you using?
      placeholder: 'e.g., 1.0.0'
    validations:
      required: true

  - type: dropdown
    id: laravel_version
    attributes:
      label: Laravel Version
      description: Which version of Laravel are you using?
      options:
        - '11.x'
        - '10.x'
        - '9.x'
        - '8.x'
        - 'Other (specify in description)'
    validations:
      required: true

  - type: dropdown
    id: php_version
    attributes:
      label: PHP Version
      description: Which version of PHP are you using?
      options:
        - '8.3'
        - '8.2'
        - '8.1'
        - '8.0'
        - 'Other (specify in description)'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Configure Scout with...
        2. Create model with...
        3. Perform search with...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Please provide a minimal code example that demonstrates the issue
      render: php
      placeholder: |
        <?php
        // Your code example here
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please include any relevant error messages or stack traces
      render: shell
      placeholder: Paste error logs here...
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your relevant configuration (remove sensitive data)
      render: php
      placeholder: |
        // config/ogini.php
        return [
            // Your configuration here
        ];
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any additional environment details that might be relevant
      placeholder: |
        - Operating System: 
        - Database: 
        - OginiSearch Server Version:
        - Queue Driver:
        - Cache Driver:
    validations:
      required: false

  - type: checkboxes
    id: additional
    attributes:
      label: Additional Information
      description: Please check any that apply
      options:
        - label: This issue affects production
        - label: This is a security vulnerability
        - label: I can consistently reproduce this issue
        - label: I am willing to submit a pull request for this issue
