name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! This helps us improve the OginiSearch Laravel Scout Driver.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Before requesting a feature, please check the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature would benefit the broader community, not just my specific use case
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions you've considered...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - 'Low - Nice to have'
        - 'Medium - Would improve my workflow'
        - 'High - Blocking my use case'
        - 'Critical - Required for production use'
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - 'Search functionality'
        - 'Performance optimization'
        - 'Configuration options'
        - 'Developer experience'
        - 'Documentation'
        - 'Testing'
        - 'Async operations'
        - 'Event system'
        - 'Error handling'
        - 'Update management'
        - 'Other'
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Provide a detailed use case or example of how this feature would be used
      placeholder: |
        Example:
        1. As a developer, I want to...
        2. So that I can...
        3. This would help me...
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about how the API should look, please share them
      render: php
      placeholder: |
        <?php
        // Example API design
        $results = Article::search('query')
            ->yourNewFeature($parameters)
            ->get();
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: Share any implementation thoughts or technical considerations...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
        - label: I can provide feedback during development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...
    validations:
      required: false
